<?php
/**
 * @file
 * Install, update, and uninstall functions for the MediaMosa development.
 */

/**
 * Moved development tool to tools section when under MediaMosa backend.
 */
function mediamosa_development_update_7000() {
  if (class_exists('mediamosa_permission')) {
    db_query('DELETE FROM {registry}');
    db_query('DELETE FROM {registry_file}');
    drupal_flush_all_caches();

    registry_rebuild();
    cache_clear_all();
  }
}
